<?php usort($this->info, function ($a, $b) {
    return strtotime($a['expiration']) > strtotime($b['expiration']);
}) ?>

<table class="subscriptions table">
    <tr>
        <th>Subscription</th>
        <th>Expiration (YYYY-MM-DD)</th>
        <th>Status</th>
        <th>Days</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($this->info as $row): ?>
        <?php

        $days = 'N/A';
        if ($row['expiration'] == 'N/A') {
            $class = 'unlimited';
            continue;
        } else {
            $currentDate = new DateTime();
            $expirationDate = DateTime::createFromFormat('Y-m-d', $row['expiration']);
            $diff = date_diff($currentDate, $expirationDate);
            $diff->format('%a');
            $days = $diff->days;
            $diff->invert == 1 ? $days = $days * (-1) : $days = $days * 1;


            if ($days <= 0) {
                $class = 'expired';
            } elseif (($days <= 14) && ($days > 0)) {
                $class = 'expiring';
            } else {
                $class = 'ok';
            }
        }

        ?>
        <tr class="<?php echo $class; ?>">
            <td class="link"><a href="<?= $row["link"]?>"><?php echo $row['name'] ?></a></td>
            <td><?php echo $row['expiration'] ?></td>
            <td><?php echo $class; ?></td>
            <td>
                <?php
                    if($days<0) {
                        echo abs($days), ' days ago';
                    }
                    else{
                        echo abs($days), ' days remaining';
                    }
                ?>
            </td>
            <td class="actions"><a href="<?= $row["edit"]?>">Edit</a></td>

        </tr>
    <?php endforeach; ?>
</table>
